### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by boddumanohar** [coding-blocks/LimitRun#1]
We need to provide better documentation. Do we want to do this as a wiki, readthedocs, or a long readme?
To start we should at least have the following documented:
1. Overview of the system
2. How to install
3. Requirements

Step-by-step walk through

**Comment by championswimmer** [comment]
A readme.md should be good to begin with

**Comment by dotslash21** [comment]
Hi! I would like to take on this issue for the Hacktoberfest challenge. Please assign me.
